package constant

const (
	GEL_OBJECT_DELIMITER        = byte(0x00)
	GEL_OBJECT_DELIMITER_LENGTH = 1

	GEL_FIELD_DELIMITER        = byte(' ') // 0x20
	GEL_FIELD_DELIMITER_LENGTH = 1
)
const (
	GEL_OBJECT_TYPE_BLOB    = "blob"
	GEL_OBJECT_TYPE_TREE    = "tree"
	GEL_OBJECT_TYPE_COMMIT  = "commit"
	GEL_OBJECT_TYPE_TAG     = "tag"
	GEL_OBJECT_TYPE_UNKNOWN = "unknown"
)

const (
	GEL_OBJECT_HEADER_BLOB    = "blob "
	GEL_OBJECT_HEADER_TREE    = "tree "
	GEL_OBJECT_HEADER_COMMIT  = "commit "
	GEL_OBJECT_HEADER_TAG     = "tag "
	GEL_OBJECT_HEADER_UNKNOWN = "unknown "
)

const (
	GEL_OBJECT_TYPE_BLOB_LENGTH    = len(GEL_OBJECT_HEADER_BLOB)
	GEL_OBJECT_TYPE_TREE_LENGTH    = len(GEL_OBJECT_HEADER_TREE)
	GEL_OBJECT_TYPE_COMMIT_LENGTH  = len(GEL_OBJECT_HEADER_COMMIT)
	GEL_OBJECT_TYPE_TAG_LENGTH     = len(GEL_OBJECT_HEADER_TAG)
	GEL_OBJECT_TYPE_UNKNOWN_LENGTH = len(GEL_OBJECT_HEADER_UNKNOWN)
)

const (
	GEL_REGULAR_FILE_PERMISSIONS    = 0644 // -rw-r--r--
	GEL_EXECUTABLE_FILE_PERMISSIONS = 0755 // -rwxr-xr-x
	GEL_DIRECTORY_PERMISSIONS       = 0755 // drwxr-xr-x
)

const (
	GEL_OBJECT_MODE_BLOB       = "100644" // non-executable file
	GEL_OBJECT_MODE_EXECUTABLE = "100755" // executable file
	GEL_OBJECT_MODE_TREE       = "040000" // directory
	GEL_OBJECT_MODE_SYMLINK    = "120000" // symbolic link
	GEL_OBJECT_MODE_COMMIT     = "160000" // gellink (submodule)
)
